title: Sysmon Configuration Change
id: 09fc5228-7e6c-11ea-addc-65bf8f9bd587
status: stable
description: Detects when sysmon configuration is modified. Licensed under DRL v1.1, original rule copyright F5, Inc.
references:
  - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
  - https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?source=Sysmon&eventID=16
author: Levi Smith - SOC Analyst II, F5 Inc
date: 2023/11/10
logsource:
    product: windows
    service: sysmon 
detection:
    selection:
        EventId: 16
    condition: selection
fields:
  - Configuration
  - ConfigurationFileHash
falsepositives:
    - Expected configuration changes from known users/services
level: medium