title: Sysmon - Possible Application Whitelisting Bypass
id: 2fb99346-7e6c-11ea-b74b-1f85c04bf8ab
status: stable
description: Detects IoC's of a system binary proxy execution exploit. Licensed under DRL v1.1, original rule copyright F5, Inc.
references:
    - https://attack.mitre.org/techniques/T1218/010/
author: Levi Smith - SOC Analyst II, F5 Inc
date: 2023/12/07
logsource:
    product: windows
    category: process_creation 
detection:
    selection:
       Image|contains: '\Windows\System32\regsvr32.exe'
       CommandLine|contains:
           - ' /i:http'
           - 'scrobj.dll'
    condition: selection
fields:
   - ProcessId
   - Image
   - Description
   - Product
   - User
   - TerminalSessionId
   - Hashes
   - ParentImage
   - ParentUser
   - ParentCommandLine
   - CurrentDirectory
   - OriginalFileName
falsepositives:
    - Authorized and expected use of regsvr32.exe
level: medium